[package]
name = "traktorhtml2txt"
version = "0.1.0"
authors = ["Paul Adenot <paul@paul.cx>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33"
kuchiki = "0.8"
chrono = "0.4"
